//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.courts.mo.gov/exchanges/ExchangeDocument/1.0")]
[System.Xml.Serialization.XmlRootAttribute("MoExchangeNotification", Namespace="http://www.courts.mo.gov/exchanges/ExchangeDocument/1.0", IsNullable=false)]
public partial class MoExchangeNotificationType {
    
    private string messageIDField;
    
    private string sourceField;
    
    private string destinationField;
    
    private string priorityField;
    
    private string deliveryAgentField;
    
    private string notificationMessageField;
    
    private DeliveryAgentHeaderType deliveryAgentHeaderField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MessageID {
        get {
            return this.messageIDField;
        }
        set {
            this.messageIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Source {
        get {
            return this.sourceField;
        }
        set {
            this.sourceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Destination {
        get {
            return this.destinationField;
        }
        set {
            this.destinationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Priority {
        get {
            return this.priorityField;
        }
        set {
            this.priorityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DeliveryAgent {
        get {
            return this.deliveryAgentField;
        }
        set {
            this.deliveryAgentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string NotificationMessage {
        get {
            return this.notificationMessageField;
        }
        set {
            this.notificationMessageField = value;
        }
    }
    
    /// <remarks/>
    public DeliveryAgentHeaderType DeliveryAgentHeader {
        get {
            return this.deliveryAgentHeaderField;
        }
        set {
            this.deliveryAgentHeaderField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.courts.mo.gov/exchanges/ExchangeDocument/1.0")]
[System.Xml.Serialization.XmlRootAttribute("DeliveryAgentHeader", Namespace="http://www.courts.mo.gov/exchanges/ExchangeDocument/1.0", IsNullable=false)]
public partial class DeliveryAgentHeaderType {
    
    private DeliveryAgentHeaderTypeWebServiceDeliveryAgent webServiceDeliveryAgentField;
    
    private DeliveryAgentHeaderTypeMQDeliveryAgent mQDeliveryAgentField;
    
    private DeliveryAgentHeaderTypeEmailDeliveryAgent emailDeliveryAgentField;
    
    private DeliveryAgentHeaderTypePagerDeliveryAgent pagerDeliveryAgentField;
    
    private DeliveryAgentHeaderTypeFTPDeliveryAgent fTPDeliveryAgentField;
    
    private DeliveryAgentHeaderTypeDatabaseDeliveryAgent databaseDeliveryAgentField;
    
    private DeliveryAgentHeaderTypePrinterDeliveryAgent printerDeliveryAgentField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DeliveryAgentHeaderTypeWebServiceDeliveryAgent WebServiceDeliveryAgent {
        get {
            return this.webServiceDeliveryAgentField;
        }
        set {
            this.webServiceDeliveryAgentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DeliveryAgentHeaderTypeMQDeliveryAgent MQDeliveryAgent {
        get {
            return this.mQDeliveryAgentField;
        }
        set {
            this.mQDeliveryAgentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DeliveryAgentHeaderTypeEmailDeliveryAgent EmailDeliveryAgent {
        get {
            return this.emailDeliveryAgentField;
        }
        set {
            this.emailDeliveryAgentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DeliveryAgentHeaderTypePagerDeliveryAgent PagerDeliveryAgent {
        get {
            return this.pagerDeliveryAgentField;
        }
        set {
            this.pagerDeliveryAgentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DeliveryAgentHeaderTypeFTPDeliveryAgent FTPDeliveryAgent {
        get {
            return this.fTPDeliveryAgentField;
        }
        set {
            this.fTPDeliveryAgentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DeliveryAgentHeaderTypeDatabaseDeliveryAgent DatabaseDeliveryAgent {
        get {
            return this.databaseDeliveryAgentField;
        }
        set {
            this.databaseDeliveryAgentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DeliveryAgentHeaderTypePrinterDeliveryAgent PrinterDeliveryAgent {
        get {
            return this.printerDeliveryAgentField;
        }
        set {
            this.printerDeliveryAgentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.courts.mo.gov/exchanges/ExchangeDocument/1.0")]
public partial class DeliveryAgentHeaderTypeWebServiceDeliveryAgent {
    
    private string webServiceTypeField;
    
    private string webServiceEndPointField;
    
    private string webServiceOperationField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string WebServiceType {
        get {
            return this.webServiceTypeField;
        }
        set {
            this.webServiceTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string WebServiceEndPoint {
        get {
            return this.webServiceEndPointField;
        }
        set {
            this.webServiceEndPointField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string WebServiceOperation {
        get {
            return this.webServiceOperationField;
        }
        set {
            this.webServiceOperationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.courts.mo.gov/exchanges/ExchangeDocument/1.0")]
public partial class MoExchangeRequestType {
    
    private MoExchangeRequestPayloadType moExchangeRequestField;
    
    private MoExchangeNotificationType moExchangeNotificationField;
    
    /// <remarks/>
    public MoExchangeRequestPayloadType MoExchangeRequest {
        get {
            return this.moExchangeRequestField;
        }
        set {
            this.moExchangeRequestField = value;
        }
    }
    
    /// <remarks/>
    public MoExchangeNotificationType MoExchangeNotification {
        get {
            return this.moExchangeNotificationField;
        }
        set {
            this.moExchangeNotificationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.courts.mo.gov/exchanges/ExchangeDocument/1.0")]
[System.Xml.Serialization.XmlRootAttribute("MoExchangeRequestPayload", Namespace="http://www.courts.mo.gov/exchanges/ExchangeDocument/1.0", IsNullable=false)]
public partial class MoExchangeRequestPayloadType {
    
    private MoExChangeHeaderType moExchangeHeaderField;
    
    private MoExchangeStructuredDataPayloadType moExchangeStructuredDataPayloadField;
    
    private MoExchangeNotificationType moExchangeNotificationField;
    
    /// <remarks/>
    public MoExChangeHeaderType MoExchangeHeader {
        get {
            return this.moExchangeHeaderField;
        }
        set {
            this.moExchangeHeaderField = value;
        }
    }
    
    /// <remarks/>
    public MoExchangeStructuredDataPayloadType MoExchangeStructuredDataPayload {
        get {
            return this.moExchangeStructuredDataPayloadField;
        }
        set {
            this.moExchangeStructuredDataPayloadField = value;
        }
    }
    
    /// <remarks/>
    public MoExchangeNotificationType MoExchangeNotification {
        get {
            return this.moExchangeNotificationField;
        }
        set {
            this.moExchangeNotificationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.courts.mo.gov/exchanges/ExchangeDocument/1.0")]
[System.Xml.Serialization.XmlRootAttribute("MoExchangeHeader", Namespace="http://www.courts.mo.gov/exchanges/ExchangeDocument/1.0", IsNullable=false)]
public partial class MoExChangeHeaderType {
    
    private string headerVersionField;
    
    private string serviceNameField;
    
    private string serviceVersionField;
    
    private string transactionNameField;
    
    private string transactionTypeField;
    
    private string messageIDField;
    
    private string messagePriorityField;
    
    private string messageTypeField;
    
    private string requestOriginatorField;
    
    private string sourceLogicalNameField;
    
    private string destinationLogicalNameField;
    
    private string notificationDestinationsField;
    
    private string sourceORIField;
    
    private string destinationORIField;
    
    private string payloadFormatField;
    
    private string futurePathField;
    
    private string delayedResponsePathField;
    
    private string pastPathField;
    
    private string logLevelField;
    
    private string errorIDField;
    
    private string userIDField;
    
    private System.DateTime creationTimestampField;
    
    private bool creationTimestampFieldSpecified;
    
    private string expiryPeriodField;
    
    private string confidentialityFlagField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string HeaderVersion {
        get {
            return this.headerVersionField;
        }
        set {
            this.headerVersionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ServiceName {
        get {
            return this.serviceNameField;
        }
        set {
            this.serviceNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ServiceVersion {
        get {
            return this.serviceVersionField;
        }
        set {
            this.serviceVersionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TransactionName {
        get {
            return this.transactionNameField;
        }
        set {
            this.transactionNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TransactionType {
        get {
            return this.transactionTypeField;
        }
        set {
            this.transactionTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MessageID {
        get {
            return this.messageIDField;
        }
        set {
            this.messageIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MessagePriority {
        get {
            return this.messagePriorityField;
        }
        set {
            this.messagePriorityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MessageType {
        get {
            return this.messageTypeField;
        }
        set {
            this.messageTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RequestOriginator {
        get {
            return this.requestOriginatorField;
        }
        set {
            this.requestOriginatorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SourceLogicalName {
        get {
            return this.sourceLogicalNameField;
        }
        set {
            this.sourceLogicalNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DestinationLogicalName {
        get {
            return this.destinationLogicalNameField;
        }
        set {
            this.destinationLogicalNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string NotificationDestinations {
        get {
            return this.notificationDestinationsField;
        }
        set {
            this.notificationDestinationsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SourceORI {
        get {
            return this.sourceORIField;
        }
        set {
            this.sourceORIField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DestinationORI {
        get {
            return this.destinationORIField;
        }
        set {
            this.destinationORIField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PayloadFormat {
        get {
            return this.payloadFormatField;
        }
        set {
            this.payloadFormatField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FuturePath {
        get {
            return this.futurePathField;
        }
        set {
            this.futurePathField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DelayedResponsePath {
        get {
            return this.delayedResponsePathField;
        }
        set {
            this.delayedResponsePathField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PastPath {
        get {
            return this.pastPathField;
        }
        set {
            this.pastPathField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LogLevel {
        get {
            return this.logLevelField;
        }
        set {
            this.logLevelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ErrorID {
        get {
            return this.errorIDField;
        }
        set {
            this.errorIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string UserID {
        get {
            return this.userIDField;
        }
        set {
            this.userIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime CreationTimestamp {
        get {
            return this.creationTimestampField;
        }
        set {
            this.creationTimestampField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CreationTimestampSpecified {
        get {
            return this.creationTimestampFieldSpecified;
        }
        set {
            this.creationTimestampFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ExpiryPeriod {
        get {
            return this.expiryPeriodField;
        }
        set {
            this.expiryPeriodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ConfidentialityFlag {
        get {
            return this.confidentialityFlagField;
        }
        set {
            this.confidentialityFlagField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.courts.mo.gov/exchanges/ExchangeDocument/1.0")]
[System.Xml.Serialization.XmlRootAttribute("MoExchangeStructuredDataPayload", Namespace="http://www.courts.mo.gov/exchanges/ExchangeDocument/1.0", IsNullable=false)]
public partial class MoExchangeStructuredDataPayloadType {
    
    private string moExchangeStructuredDataField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MoExchangeStructuredData {
        get {
            return this.moExchangeStructuredDataField;
        }
        set {
            this.moExchangeStructuredDataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.courts.mo.gov/exchanges/ExchangeDocument/1.0")]
public partial class DeliveryAgentHeaderTypeMQDeliveryAgent {
    
    private string queueManagerField;
    
    private string queueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string QueueManager {
        get {
            return this.queueManagerField;
        }
        set {
            this.queueManagerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Queue {
        get {
            return this.queueField;
        }
        set {
            this.queueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.courts.mo.gov/exchanges/ExchangeDocument/1.0")]
public partial class DeliveryAgentHeaderTypeEmailDeliveryAgent {
    
    private string toEmailIDField;
    
    private string fromEmailIDField;
    
    private string subjectField;
    
    private AttachmentType[] attachmentsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ToEmailID {
        get {
            return this.toEmailIDField;
        }
        set {
            this.toEmailIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FromEmailID {
        get {
            return this.fromEmailIDField;
        }
        set {
            this.fromEmailIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Subject {
        get {
            return this.subjectField;
        }
        set {
            this.subjectField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Attachment", IsNullable=false)]
    public AttachmentType[] Attachments {
        get {
            return this.attachmentsField;
        }
        set {
            this.attachmentsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.courts.mo.gov/exchanges/ExchangeDocument/1.0")]
[System.Xml.Serialization.XmlRootAttribute("Attachment", Namespace="http://www.courts.mo.gov/exchanges/ExchangeDocument/1.0", IsNullable=false)]
public partial class AttachmentType {
    
    private string mIMETypeField;
    
    private string fileNameField;
    
    private string dataField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MIMEType {
        get {
            return this.mIMETypeField;
        }
        set {
            this.mIMETypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FileName {
        get {
            return this.fileNameField;
        }
        set {
            this.fileNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Data {
        get {
            return this.dataField;
        }
        set {
            this.dataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.courts.mo.gov/exchanges/ExchangeDocument/1.0")]
public partial class DeliveryAgentHeaderTypePagerDeliveryAgent {
    
    private string pagerNumberField;
    
    private string senderNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PagerNumber {
        get {
            return this.pagerNumberField;
        }
        set {
            this.pagerNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SenderName {
        get {
            return this.senderNameField;
        }
        set {
            this.senderNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.courts.mo.gov/exchanges/ExchangeDocument/1.0")]
public partial class DeliveryAgentHeaderTypeFTPDeliveryAgent {
    
    private string fTPAddressField;
    
    private string userNameField;
    
    private string passwordField;
    
    private AttachmentType[] attachmentsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FTPAddress {
        get {
            return this.fTPAddressField;
        }
        set {
            this.fTPAddressField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string UserName {
        get {
            return this.userNameField;
        }
        set {
            this.userNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Password {
        get {
            return this.passwordField;
        }
        set {
            this.passwordField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Attachment", IsNullable=false)]
    public AttachmentType[] Attachments {
        get {
            return this.attachmentsField;
        }
        set {
            this.attachmentsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.courts.mo.gov/exchanges/ExchangeDocument/1.0")]
public partial class DeliveryAgentHeaderTypeDatabaseDeliveryAgent {
    
    private string databaseConnectURLField;
    
    private string databasePersistanceObjectField;
    
    private DeliveryAgentHeaderTypeDatabaseDeliveryAgentMap[] databaseColumnMappingField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DatabaseConnectURL {
        get {
            return this.databaseConnectURLField;
        }
        set {
            this.databaseConnectURLField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DatabasePersistanceObject {
        get {
            return this.databasePersistanceObjectField;
        }
        set {
            this.databasePersistanceObjectField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Map", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public DeliveryAgentHeaderTypeDatabaseDeliveryAgentMap[] DatabaseColumnMapping {
        get {
            return this.databaseColumnMappingField;
        }
        set {
            this.databaseColumnMappingField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.courts.mo.gov/exchanges/ExchangeDocument/1.0")]
public partial class DeliveryAgentHeaderTypeDatabaseDeliveryAgentMap {
    
    private string columnField;
    
    private string elementField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Column {
        get {
            return this.columnField;
        }
        set {
            this.columnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Element {
        get {
            return this.elementField;
        }
        set {
            this.elementField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.courts.mo.gov/exchanges/ExchangeDocument/1.0")]
public partial class DeliveryAgentHeaderTypePrinterDeliveryAgent {
    
    private string printerServerField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PrinterServer {
        get {
            return this.printerServerField;
        }
        set {
            this.printerServerField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.courts.mo.gov/exchanges/ExchangeDocument/1.0")]
[System.Xml.Serialization.XmlRootAttribute("MoExchangeException", Namespace="http://www.courts.mo.gov/exchanges/ExchangeDocument/1.0", IsNullable=false)]
public partial class MoExchangeExceptionType {
    
    private MoExchangeBusinessExceptionType[] moExchangeBusinessExceptionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("MoExchangeBusinessException", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public MoExchangeBusinessExceptionType[] MoExchangeBusinessException {
        get {
            return this.moExchangeBusinessExceptionField;
        }
        set {
            this.moExchangeBusinessExceptionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.courts.mo.gov/exchanges/ExchangeDocument/1.0")]
[System.Xml.Serialization.XmlRootAttribute("MoExchangeBusinessException", Namespace="http://www.courts.mo.gov/exchanges/ExchangeDocument/1.0", IsNullable=false)]
public partial class MoExchangeBusinessExceptionType {
    
    private string serviceNameField;
    
    private System.DateTime exceptionTimestampField;
    
    private bool exceptionTimestampFieldSpecified;
    
    private object originalPayloadField;
    
    private ExceptionDetailType[] exceptionDetailField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ServiceName {
        get {
            return this.serviceNameField;
        }
        set {
            this.serviceNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime ExceptionTimestamp {
        get {
            return this.exceptionTimestampField;
        }
        set {
            this.exceptionTimestampField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ExceptionTimestampSpecified {
        get {
            return this.exceptionTimestampFieldSpecified;
        }
        set {
            this.exceptionTimestampFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public object OriginalPayload {
        get {
            return this.originalPayloadField;
        }
        set {
            this.originalPayloadField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ExceptionDetail", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ExceptionDetailType[] ExceptionDetail {
        get {
            return this.exceptionDetailField;
        }
        set {
            this.exceptionDetailField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.courts.mo.gov/exchanges/ExchangeDocument/1.0")]
[System.Xml.Serialization.XmlRootAttribute("ExceptionDetail", Namespace="http://www.courts.mo.gov/exchanges/ExchangeDocument/1.0", IsNullable=false)]
public partial class ExceptionDetailType {
    
    private string exceptionComponentIDField;
    
    private string exceptionSeverityField;
    
    private string exceptionCodeField;
    
    private string exceptionMessageTextField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ExceptionComponentID {
        get {
            return this.exceptionComponentIDField;
        }
        set {
            this.exceptionComponentIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ExceptionSeverity {
        get {
            return this.exceptionSeverityField;
        }
        set {
            this.exceptionSeverityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ExceptionCode {
        get {
            return this.exceptionCodeField;
        }
        set {
            this.exceptionCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ExceptionMessageText {
        get {
            return this.exceptionMessageTextField;
        }
        set {
            this.exceptionMessageTextField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.courts.mo.gov/exchanges/ExchangeDocument/1.0")]
[System.Xml.Serialization.XmlRootAttribute("Attachments", Namespace="http://www.courts.mo.gov/exchanges/ExchangeDocument/1.0", IsNullable=false)]
public partial class AttachmentsType {
    
    private AttachmentType[] attachmentField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Attachment")]
    public AttachmentType[] Attachment {
        get {
            return this.attachmentField;
        }
        set {
            this.attachmentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.courts.mo.gov/exchanges/ExchangeDocument/1.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.courts.mo.gov/exchanges/ExchangeDocument/1.0", IsNullable=false)]
public partial class MoExchangeMessage {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("MoExchangeRequest", typeof(MoExchangeRequestPayloadType))]
    [System.Xml.Serialization.XmlElementAttribute("MoExchangeResponse", typeof(MoExchangeResponsePayloadType))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.courts.mo.gov/exchanges/ExchangeDocument/1.0")]
[System.Xml.Serialization.XmlRootAttribute("MoExchangeResponse", Namespace="http://www.courts.mo.gov/exchanges/ExchangeDocument/1.0", IsNullable=false)]
public partial class MoExchangeResponsePayloadType {
    
    private MoExChangeHeaderType moExchangeHeaderField;
    
    private MoExchangeStructuredDataPayloadType moExchangeStructuredDataPayloadField;
    
    private MoExchangeNotificationType moExchangeNotificationField;
    
    private MoExchangeBusinessExceptionType[] moExchangeExceptionField;
    
    /// <remarks/>
    public MoExChangeHeaderType MoExchangeHeader {
        get {
            return this.moExchangeHeaderField;
        }
        set {
            this.moExchangeHeaderField = value;
        }
    }
    
    /// <remarks/>
    public MoExchangeStructuredDataPayloadType MoExchangeStructuredDataPayload {
        get {
            return this.moExchangeStructuredDataPayloadField;
        }
        set {
            this.moExchangeStructuredDataPayloadField = value;
        }
    }
    
    /// <remarks/>
    public MoExchangeNotificationType MoExchangeNotification {
        get {
            return this.moExchangeNotificationField;
        }
        set {
            this.moExchangeNotificationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("MoExchangeBusinessException", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public MoExchangeBusinessExceptionType[] MoExchangeException {
        get {
            return this.moExchangeExceptionField;
        }
        set {
            this.moExchangeExceptionField = value;
        }
    }
}
