//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.courts.mo.gov/exchanges/MoEcfExchange/1.0")]
[System.Xml.Serialization.XmlRootAttribute("MoEcfExchange", Namespace="http://www.courts.mo.gov/exchanges/MoEcfExchange/1.0", IsNullable=false)]
public partial class MoEcfExchangeType : ComplexObjectType {
    
    private PersonType[] personField;
    
    private OrganizationType[] organizationField;
    
    private ContactInformationType[] contactInformationField;
    
    private PersonContactInformationAssociationType[] personContactInformationAssociationField;
    
    private OrganizationContactInformationAssociationType[] organizationContactInformationAssociationField;
    
    private CaseType1 caseField;
    
    private EntityCaseAssociationType[] entityCaseAssociationField;
    
    private IdentificationType[] identificationField;
    
    private ObligationType1 feeField;
    
    private TextType commentTextField;
    
    private DocumentType1[] primaryDocumentField;
    
    private EntityDocumentAssociationType[] entityDocumentAssociationField;
    
    private MetadataType1[] metadataField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Person", Namespace="http://niem.gov/niem/niem-core/2.0", IsNullable=true)]
    public PersonType[] Person {
        get {
            return this.personField;
        }
        set {
            this.personField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Organization", Namespace="http://niem.gov/niem/niem-core/2.0", IsNullable=true)]
    public OrganizationType[] Organization {
        get {
            return this.organizationField;
        }
        set {
            this.organizationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ContactInformation", Namespace="http://niem.gov/niem/niem-core/2.0", IsNullable=true)]
    public ContactInformationType[] ContactInformation {
        get {
            return this.contactInformationField;
        }
        set {
            this.contactInformationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PersonContactInformationAssociation", Namespace="http://niem.gov/niem/niem-core/2.0", IsNullable=true)]
    public PersonContactInformationAssociationType[] PersonContactInformationAssociation {
        get {
            return this.personContactInformationAssociationField;
        }
        set {
            this.personContactInformationAssociationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("OrganizationContactInformationAssociation", Namespace="http://niem.gov/niem/niem-core/2.0", IsNullable=true)]
    public OrganizationContactInformationAssociationType[] OrganizationContactInformationAssociation {
        get {
            return this.organizationContactInformationAssociationField;
        }
        set {
            this.organizationContactInformationAssociationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://niem.gov/niem/domains/jxdm/4.1", IsNullable=true)]
    public CaseType1 Case {
        get {
            return this.caseField;
        }
        set {
            this.caseField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("EntityCaseAssociation", Namespace="http://www.courts.mo.gov/exchanges/MoEcfExchangeExtensions/1.0")]
    public EntityCaseAssociationType[] EntityCaseAssociation {
        get {
            return this.entityCaseAssociationField;
        }
        set {
            this.entityCaseAssociationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Identification", Namespace="http://niem.gov/niem/niem-core/2.0", IsNullable=true)]
    public IdentificationType[] Identification {
        get {
            return this.identificationField;
        }
        set {
            this.identificationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.courts.mo.gov/exchanges/MoEcfExchangeExtensions/1.0")]
    public ObligationType1 Fee {
        get {
            return this.feeField;
        }
        set {
            this.feeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://niem.gov/niem/niem-core/2.0", IsNullable=true)]
    public TextType CommentText {
        get {
            return this.commentTextField;
        }
        set {
            this.commentTextField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PrimaryDocument", Namespace="http://www.courts.mo.gov/exchanges/MoEcfExchangeExtensions/1.0")]
    public DocumentType1[] PrimaryDocument {
        get {
            return this.primaryDocumentField;
        }
        set {
            this.primaryDocumentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("EntityDocumentAssociation", Namespace="http://www.courts.mo.gov/exchanges/MoEcfExchangeExtensions/1.0")]
    public EntityDocumentAssociationType[] EntityDocumentAssociation {
        get {
            return this.entityDocumentAssociationField;
        }
        set {
            this.entityDocumentAssociationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Metadata", Namespace="http://niem.gov/niem/niem-core/2.0", IsNullable=true)]
    public MetadataType1[] Metadata {
        get {
            return this.metadataField;
        }
        set {
            this.metadataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://niem.gov/niem/niem-core/2.0")]
[System.Xml.Serialization.XmlRootAttribute("Person", Namespace="http://niem.gov/niem/niem-core/2.0", IsNullable=true)]
public partial class PersonType : ComplexObjectType {
    
    private DateType personBirthDateField;
    
    private PersonNameType personNameField;
    
    private IdentificationType personOtherIdentificationField;
    
    private SEXCodeType itemField;
    
    private IdentificationType personSSNIdentificationField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public DateType PersonBirthDate {
        get {
            return this.personBirthDateField;
        }
        set {
            this.personBirthDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public PersonNameType PersonName {
        get {
            return this.personNameField;
        }
        set {
            this.personNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public IdentificationType PersonOtherIdentification {
        get {
            return this.personOtherIdentificationField;
        }
        set {
            this.personOtherIdentificationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PersonSexCode", IsNullable=true)]
    public SEXCodeType Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public IdentificationType PersonSSNIdentification {
        get {
            return this.personSSNIdentificationField;
        }
        set {
            this.personSSNIdentificationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://niem.gov/niem/niem-core/2.0")]
[System.Xml.Serialization.XmlRootAttribute("PersonBirthDate", Namespace="http://niem.gov/niem/niem-core/2.0", IsNullable=true)]
public partial class DateType : ComplexObjectType {
    
    private date itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Date", IsNullable=true)]
    public date Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://niem.gov/niem/proxy/xsd/2.0")]
[System.Xml.Serialization.XmlRootAttribute("Date", Namespace="http://niem.gov/niem/niem-core/2.0", IsNullable=true)]
public partial class date {
    
    private string idField;
    
    private string metadataField;
    
    private string linkMetadataField;
    
    private System.DateTime valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://niem.gov/niem/structures/2.0", DataType="ID")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://niem.gov/niem/structures/2.0", DataType="IDREFS")]
    public string metadata {
        get {
            return this.metadataField;
        }
        set {
            this.metadataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://niem.gov/niem/structures/2.0", DataType="IDREFS")]
    public string linkMetadata {
        get {
            return this.linkMetadataField;
        }
        set {
            this.linkMetadataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType="date")]
    public System.DateTime Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://niem.gov/niem/proxy/xsd/2.0")]
[System.Xml.Serialization.XmlRootAttribute("BinaryBase64Object", Namespace="http://niem.gov/niem/niem-core/2.0", IsNullable=true)]
public partial class base64Binary {
    
    private string idField;
    
    private string metadataField;
    
    private string linkMetadataField;
    
    private byte[] valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://niem.gov/niem/structures/2.0", DataType="ID")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://niem.gov/niem/structures/2.0", DataType="IDREFS")]
    public string metadata {
        get {
            return this.metadataField;
        }
        set {
            this.metadataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://niem.gov/niem/structures/2.0", DataType="IDREFS")]
    public string linkMetadata {
        get {
            return this.linkMetadataField;
        }
        set {
            this.linkMetadataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType="base64Binary")]
    public byte[] Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(AmountType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://niem.gov/niem/proxy/xsd/2.0")]
public partial class @decimal {
    
    private string idField;
    
    private string metadataField;
    
    private string linkMetadataField;
    
    private decimal valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://niem.gov/niem/structures/2.0", DataType="ID")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://niem.gov/niem/structures/2.0", DataType="IDREFS")]
    public string metadata {
        get {
            return this.metadataField;
        }
        set {
            this.metadataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://niem.gov/niem/structures/2.0", DataType="IDREFS")]
    public string linkMetadata {
        get {
            return this.linkMetadataField;
        }
        set {
            this.linkMetadataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public decimal Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://niem.gov/niem/niem-core/2.0")]
[System.Xml.Serialization.XmlRootAttribute("ObligationDueAmount", Namespace="http://niem.gov/niem/niem-core/2.0", IsNullable=true)]
public partial class AmountType : @decimal {
    
    private string currencyCodeField;
    
    private string currencyTextField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="token")]
    public string currencyCode {
        get {
            return this.currencyCodeField;
        }
        set {
            this.currencyCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
    public string currencyText {
        get {
            return this.currencyTextField;
        }
        set {
            this.currencyTextField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://niem.gov/niem/iso_3166/2.0")]
[System.Xml.Serialization.XmlRootAttribute("LocationCountryISO3166Alpha2Code", Namespace="http://niem.gov/niem/niem-core/2.0", IsNullable=true)]
public partial class CountryAlpha2CodeType {
    
    private string idField;
    
    private string metadataField;
    
    private string linkMetadataField;
    
    private CountryAlpha2CodeSimpleType valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://niem.gov/niem/structures/2.0", DataType="ID")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://niem.gov/niem/structures/2.0", DataType="IDREFS")]
    public string metadata {
        get {
            return this.metadataField;
        }
        set {
            this.metadataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://niem.gov/niem/structures/2.0", DataType="IDREFS")]
    public string linkMetadata {
        get {
            return this.linkMetadataField;
        }
        set {
            this.linkMetadataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public CountryAlpha2CodeSimpleType Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://niem.gov/niem/iso_3166/2.0")]
public enum CountryAlpha2CodeSimpleType {
    
    /// <remarks/>
    AD,
    
    /// <remarks/>
    AE,
    
    /// <remarks/>
    AF,
    
    /// <remarks/>
    AG,
    
    /// <remarks/>
    AI,
    
    /// <remarks/>
    AL,
    
    /// <remarks/>
    AM,
    
    /// <remarks/>
    AN,
    
    /// <remarks/>
    AO,
    
    /// <remarks/>
    AQ,
    
    /// <remarks/>
    AR,
    
    /// <remarks/>
    AS,
    
    /// <remarks/>
    AT,
    
    /// <remarks/>
    AU,
    
    /// <remarks/>
    AW,
    
    /// <remarks/>
    AX,
    
    /// <remarks/>
    AZ,
    
    /// <remarks/>
    BA,
    
    /// <remarks/>
    BB,
    
    /// <remarks/>
    BD,
    
    /// <remarks/>
    BE,
    
    /// <remarks/>
    BF,
    
    /// <remarks/>
    BG,
    
    /// <remarks/>
    BH,
    
    /// <remarks/>
    BI,
    
    /// <remarks/>
    BJ,
    
    /// <remarks/>
    BM,
    
    /// <remarks/>
    BN,
    
    /// <remarks/>
    BO,
    
    /// <remarks/>
    BR,
    
    /// <remarks/>
    BS,
    
    /// <remarks/>
    BT,
    
    /// <remarks/>
    BV,
    
    /// <remarks/>
    BW,
    
    /// <remarks/>
    BY,
    
    /// <remarks/>
    BZ,
    
    /// <remarks/>
    CA,
    
    /// <remarks/>
    CC,
    
    /// <remarks/>
    CD,
    
    /// <remarks/>
    CF,
    
    /// <remarks/>
    CG,
    
    /// <remarks/>
    CH,
    
    /// <remarks/>
    CI,
    
    /// <remarks/>
    CK,
    
    /// <remarks/>
    CL,
    
    /// <remarks/>
    CM,
    
    /// <remarks/>
    CN,
    
    /// <remarks/>
    CO,
    
    /// <remarks/>
    CR,
    
    /// <remarks/>
    CU,
    
    /// <remarks/>
    CV,
    
    /// <remarks/>
    CX,
    
    /// <remarks/>
    CY,
    
    /// <remarks/>
    CZ,
    
    /// <remarks/>
    DE,
    
    /// <remarks/>
    DJ,
    
    /// <remarks/>
    DK,
    
    /// <remarks/>
    DM,
    
    /// <remarks/>
    DO,
    
    /// <remarks/>
    DZ,
    
    /// <remarks/>
    EC,
    
    /// <remarks/>
    EE,
    
    /// <remarks/>
    EG,
    
    /// <remarks/>
    EH,
    
    /// <remarks/>
    ER,
    
    /// <remarks/>
    ES,
    
    /// <remarks/>
    ET,
    
    /// <remarks/>
    FI,
    
    /// <remarks/>
    FJ,
    
    /// <remarks/>
    FK,
    
    /// <remarks/>
    FM,
    
    /// <remarks/>
    FO,
    
    /// <remarks/>
    FR,
    
    /// <remarks/>
    GA,
    
    /// <remarks/>
    GB,
    
    /// <remarks/>
    GD,
    
    /// <remarks/>
    GE,
    
    /// <remarks/>
    GF,
    
    /// <remarks/>
    GG,
    
    /// <remarks/>
    GH,
    
    /// <remarks/>
    GI,
    
    /// <remarks/>
    GL,
    
    /// <remarks/>
    GM,
    
    /// <remarks/>
    GN,
    
    /// <remarks/>
    GP,
    
    /// <remarks/>
    GQ,
    
    /// <remarks/>
    GR,
    
    /// <remarks/>
    GS,
    
    /// <remarks/>
    GT,
    
    /// <remarks/>
    GU,
    
    /// <remarks/>
    GW,
    
    /// <remarks/>
    GY,
    
    /// <remarks/>
    HK,
    
    /// <remarks/>
    HM,
    
    /// <remarks/>
    HN,
    
    /// <remarks/>
    HR,
    
    /// <remarks/>
    HT,
    
    /// <remarks/>
    HU,
    
    /// <remarks/>
    ID,
    
    /// <remarks/>
    IE,
    
    /// <remarks/>
    IL,
    
    /// <remarks/>
    IM,
    
    /// <remarks/>
    IN,
    
    /// <remarks/>
    IO,
    
    /// <remarks/>
    IQ,
    
    /// <remarks/>
    IR,
    
    /// <remarks/>
    IS,
    
    /// <remarks/>
    IT,
    
    /// <remarks/>
    JE,
    
    /// <remarks/>
    JM,
    
    /// <remarks/>
    JO,
    
    /// <remarks/>
    JP,
    
    /// <remarks/>
    KE,
    
    /// <remarks/>
    KG,
    
    /// <remarks/>
    KH,
    
    /// <remarks/>
    KI,
    
    /// <remarks/>
    KM,
    
    /// <remarks/>
    KN,
    
    /// <remarks/>
    KP,
    
    /// <remarks/>
    KR,
    
    /// <remarks/>
    KW,
    
    /// <remarks/>
    KY,
    
    /// <remarks/>
    KZ,
    
    /// <remarks/>
    LA,
    
    /// <remarks/>
    LB,
    
    /// <remarks/>
    LC,
    
    /// <remarks/>
    LI,
    
    /// <remarks/>
    LK,
    
    /// <remarks/>
    LR,
    
    /// <remarks/>
    LS,
    
    /// <remarks/>
    LT,
    
    /// <remarks/>
    LU,
    
    /// <remarks/>
    LV,
    
    /// <remarks/>
    LY,
    
    /// <remarks/>
    MA,
    
    /// <remarks/>
    MC,
    
    /// <remarks/>
    MD,
    
    /// <remarks/>
    ME,
    
    /// <remarks/>
    MG,
    
    /// <remarks/>
    MH,
    
    /// <remarks/>
    MK,
    
    /// <remarks/>
    ML,
    
    /// <remarks/>
    MM,
    
    /// <remarks/>
    MN,
    
    /// <remarks/>
    MO,
    
    /// <remarks/>
    MP,
    
    /// <remarks/>
    MQ,
    
    /// <remarks/>
    MR,
    
    /// <remarks/>
    MS,
    
    /// <remarks/>
    MT,
    
    /// <remarks/>
    MU,
    
    /// <remarks/>
    MV,
    
    /// <remarks/>
    MW,
    
    /// <remarks/>
    MX,
    
    /// <remarks/>
    MY,
    
    /// <remarks/>
    MZ,
    
    /// <remarks/>
    NA,
    
    /// <remarks/>
    NC,
    
    /// <remarks/>
    NE,
    
    /// <remarks/>
    NF,
    
    /// <remarks/>
    NG,
    
    /// <remarks/>
    NI,
    
    /// <remarks/>
    NL,
    
    /// <remarks/>
    NO,
    
    /// <remarks/>
    NP,
    
    /// <remarks/>
    NR,
    
    /// <remarks/>
    NU,
    
    /// <remarks/>
    NZ,
    
    /// <remarks/>
    OM,
    
    /// <remarks/>
    PA,
    
    /// <remarks/>
    PE,
    
    /// <remarks/>
    PF,
    
    /// <remarks/>
    PG,
    
    /// <remarks/>
    PH,
    
    /// <remarks/>
    PK,
    
    /// <remarks/>
    PL,
    
    /// <remarks/>
    PM,
    
    /// <remarks/>
    PN,
    
    /// <remarks/>
    PR,
    
    /// <remarks/>
    PS,
    
    /// <remarks/>
    PT,
    
    /// <remarks/>
    PW,
    
    /// <remarks/>
    PY,
    
    /// <remarks/>
    QA,
    
    /// <remarks/>
    RE,
    
    /// <remarks/>
    RO,
    
    /// <remarks/>
    RS,
    
    /// <remarks/>
    RU,
    
    /// <remarks/>
    RW,
    
    /// <remarks/>
    SA,
    
    /// <remarks/>
    SB,
    
    /// <remarks/>
    SC,
    
    /// <remarks/>
    SD,
    
    /// <remarks/>
    SE,
    
    /// <remarks/>
    SG,
    
    /// <remarks/>
    SH,
    
    /// <remarks/>
    SI,
    
    /// <remarks/>
    SJ,
    
    /// <remarks/>
    SK,
    
    /// <remarks/>
    SL,
    
    /// <remarks/>
    SM,
    
    /// <remarks/>
    SN,
    
    /// <remarks/>
    SO,
    
    /// <remarks/>
    SR,
    
    /// <remarks/>
    ST,
    
    /// <remarks/>
    SV,
    
    /// <remarks/>
    SY,
    
    /// <remarks/>
    SZ,
    
    /// <remarks/>
    TC,
    
    /// <remarks/>
    TD,
    
    /// <remarks/>
    TF,
    
    /// <remarks/>
    TG,
    
    /// <remarks/>
    TH,
    
    /// <remarks/>
    TJ,
    
    /// <remarks/>
    TK,
    
    /// <remarks/>
    TL,
    
    /// <remarks/>
    TM,
    
    /// <remarks/>
    TN,
    
    /// <remarks/>
    TO,
    
    /// <remarks/>
    TR,
    
    /// <remarks/>
    TT,
    
    /// <remarks/>
    TV,
    
    /// <remarks/>
    TW,
    
    /// <remarks/>
    TZ,
    
    /// <remarks/>
    UA,
    
    /// <remarks/>
    UG,
    
    /// <remarks/>
    UM,
    
    /// <remarks/>
    US,
    
    /// <remarks/>
    UY,
    
    /// <remarks/>
    UZ,
    
    /// <remarks/>
    VA,
    
    /// <remarks/>
    VC,
    
    /// <remarks/>
    VE,
    
    /// <remarks/>
    VG,
    
    /// <remarks/>
    VI,
    
    /// <remarks/>
    VN,
    
    /// <remarks/>
    VU,
    
    /// <remarks/>
    WF,
    
    /// <remarks/>
    WS,
    
    /// <remarks/>
    YE,
    
    /// <remarks/>
    YT,
    
    /// <remarks/>
    ZA,
    
    /// <remarks/>
    ZM,
    
    /// <remarks/>
    ZW,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://niem.gov/niem/usps_states/2.0")]
[System.Xml.Serialization.XmlRootAttribute("LocationStateUSPostalServiceCode", Namespace="http://niem.gov/niem/niem-core/2.0", IsNullable=true)]
public partial class USStateCodeType {
    
    private string idField;
    
    private string metadataField;
    
    private string linkMetadataField;
    
    private USStateCodeSimpleType valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://niem.gov/niem/structures/2.0", DataType="ID")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://niem.gov/niem/structures/2.0", DataType="IDREFS")]
    public string metadata {
        get {
            return this.metadataField;
        }
        set {
            this.metadataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://niem.gov/niem/structures/2.0", DataType="IDREFS")]
    public string linkMetadata {
        get {
            return this.linkMetadataField;
        }
        set {
            this.linkMetadataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public USStateCodeSimpleType Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://niem.gov/niem/usps_states/2.0")]
public enum USStateCodeSimpleType {
    
    /// <remarks/>
    AA,
    
    /// <remarks/>
    AE,
    
    /// <remarks/>
    AK,
    
    /// <remarks/>
    AL,
    
    /// <remarks/>
    AP,
    
    /// <remarks/>
    AR,
    
    /// <remarks/>
    AS,
    
    /// <remarks/>
    AZ,
    
    /// <remarks/>
    CA,
    
    /// <remarks/>
    CO,
    
    /// <remarks/>
    CT,
    
    /// <remarks/>
    DC,
    
    /// <remarks/>
    DE,
    
    /// <remarks/>
    FL,
    
    /// <remarks/>
    FM,
    
    /// <remarks/>
    GA,
    
    /// <remarks/>
    GU,
    
    /// <remarks/>
    HI,
    
    /// <remarks/>
    IA,
    
    /// <remarks/>
    ID,
    
    /// <remarks/>
    IL,
    
    /// <remarks/>
    IN,
    
    /// <remarks/>
    KS,
    
    /// <remarks/>
    KY,
    
    /// <remarks/>
    LA,
    
    /// <remarks/>
    MA,
    
    /// <remarks/>
    MD,
    
    /// <remarks/>
    ME,
    
    /// <remarks/>
    MH,
    
    /// <remarks/>
    MI,
    
    /// <remarks/>
    MN,
    
    /// <remarks/>
    MO,
    
    /// <remarks/>
    MP,
    
    /// <remarks/>
    MS,
    
    /// <remarks/>
    MT,
    
    /// <remarks/>
    NC,
    
    /// <remarks/>
    ND,
    
    /// <remarks/>
    NE,
    
    /// <remarks/>
    NH,
    
    /// <remarks/>
    NJ,
    
    /// <remarks/>
    NM,
    
    /// <remarks/>
    NV,
    
    /// <remarks/>
    NY,
    
    /// <remarks/>
    OH,
    
    /// <remarks/>
    OK,
    
    /// <remarks/>
    OR,
    
    /// <remarks/>
    PA,
    
    /// <remarks/>
    PR,
    
    /// <remarks/>
    PW,
    
    /// <remarks/>
    RI,
    
    /// <remarks/>
    SC,
    
    /// <remarks/>
    SD,
    
    /// <remarks/>
    TN,
    
    /// <remarks/>
    TX,
    
    /// <remarks/>
    UT,
    
    /// <remarks/>
    VA,
    
    /// <remarks/>
    VI,
    
    /// <remarks/>
    VT,
    
    /// <remarks/>
    WA,
    
    /// <remarks/>
    WI,
    
    /// <remarks/>
    WV,
    
    /// <remarks/>
    WY,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://niem.gov/niem/fbi/2.0")]
[System.Xml.Serialization.XmlRootAttribute("PersonSexCode", Namespace="http://niem.gov/niem/niem-core/2.0", IsNullable=true)]
public partial class SEXCodeType {
    
    private string idField;
    
    private string metadataField;
    
    private string linkMetadataField;
    
    private SEXCodeSimpleType valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://niem.gov/niem/structures/2.0", DataType="ID")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://niem.gov/niem/structures/2.0", DataType="IDREFS")]
    public string metadata {
        get {
            return this.metadataField;
        }
        set {
            this.metadataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://niem.gov/niem/structures/2.0", DataType="IDREFS")]
    public string linkMetadata {
        get {
            return this.linkMetadataField;
        }
        set {
            this.linkMetadataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public SEXCodeSimpleType Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://niem.gov/niem/fbi/2.0")]
public enum SEXCodeSimpleType {
    
    /// <remarks/>
    F,
    
    /// <remarks/>
    M,
    
    /// <remarks/>
    U,
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(MetadataType1))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://niem.gov/niem/structures/2.0")]
public abstract partial class MetadataType {
    
    private string idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="ID")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="MetadataType", Namespace="http://niem.gov/niem/niem-core/2.0")]
[System.Xml.Serialization.XmlRootAttribute("Metadata", Namespace="http://niem.gov/niem/niem-core/2.0", IsNullable=true)]
public partial class MetadataType1 : MetadataType {
    
    private TextType sensitivityTextField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public TextType SensitivityText {
        get {
            return this.sensitivityTextField;
        }
        set {
            this.sensitivityTextField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ProperNameTextType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(PersonNameTextType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://niem.gov/niem/niem-core/2.0")]
[System.Xml.Serialization.XmlRootAttribute("AssociationDescriptionText", Namespace="http://www.courts.mo.gov/exchanges/MoEcfExchangeExtensions/1.0", IsNullable=false)]
public partial class TextType : @string {
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(TextType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ProperNameTextType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(PersonNameTextType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://niem.gov/niem/proxy/xsd/2.0")]
[System.Xml.Serialization.XmlRootAttribute("PaymentCourtDebitAccount", Namespace="http://www.courts.mo.gov/exchanges/MoEcfExchange/1.0", IsNullable=true)]
public partial class @string {
    
    private string idField;
    
    private string metadataField;
    
    private string linkMetadataField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://niem.gov/niem/structures/2.0", DataType="ID")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://niem.gov/niem/structures/2.0", DataType="IDREFS")]
    public string metadata {
        get {
            return this.metadataField;
        }
        set {
            this.metadataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://niem.gov/niem/structures/2.0", DataType="IDREFS")]
    public string linkMetadata {
        get {
            return this.linkMetadataField;
        }
        set {
            this.linkMetadataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(PersonNameTextType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://niem.gov/niem/niem-core/2.0")]
[System.Xml.Serialization.XmlRootAttribute("LocationCityName", Namespace="http://niem.gov/niem/niem-core/2.0", IsNullable=true)]
public partial class ProperNameTextType : TextType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://niem.gov/niem/niem-core/2.0")]
[System.Xml.Serialization.XmlRootAttribute("PersonGivenName", Namespace="http://niem.gov/niem/niem-core/2.0", IsNullable=true)]
public partial class PersonNameTextType : ProperNameTextType {
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(CaseAugmentationType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://niem.gov/niem/structures/2.0")]
public abstract partial class AugmentationType {
    
    private string idField;
    
    private string metadataField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="ID")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="IDREFS")]
    public string metadata {
        get {
            return this.metadataField;
        }
        set {
            this.metadataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://niem.gov/niem/domains/jxdm/4.1")]
[System.Xml.Serialization.XmlRootAttribute("CaseAugmentation", Namespace="http://niem.gov/niem/domains/jxdm/4.1", IsNullable=false)]
public partial class CaseAugmentationType : AugmentationType {
    
    private CourtType caseCourtField;
    
    private IdentificationType caseOtherIdentificationField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public CourtType CaseCourt {
        get {
            return this.caseCourtField;
        }
        set {
            this.caseCourtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public IdentificationType CaseOtherIdentification {
        get {
            return this.caseOtherIdentificationField;
        }
        set {
            this.caseOtherIdentificationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://niem.gov/niem/domains/jxdm/4.1")]
[System.Xml.Serialization.XmlRootAttribute("CaseCourt", Namespace="http://niem.gov/niem/domains/jxdm/4.1", IsNullable=true)]
public partial class CourtType : OrganizationType {
    
    private TextType courtDivisionTextField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public TextType CourtDivisionText {
        get {
            return this.courtDivisionTextField;
        }
        set {
            this.courtDivisionTextField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(CourtType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://niem.gov/niem/niem-core/2.0")]
[System.Xml.Serialization.XmlRootAttribute("Organization", Namespace="http://niem.gov/niem/niem-core/2.0", IsNullable=true)]
public partial class OrganizationType : ComplexObjectType {
    
    private TextType organizationNameField;
    
    private IdentificationType[] organizationOtherIdentificationField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public TextType OrganizationName {
        get {
            return this.organizationNameField;
        }
        set {
            this.organizationNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("OrganizationOtherIdentification", IsNullable=true)]
    public IdentificationType[] OrganizationOtherIdentification {
        get {
            return this.organizationOtherIdentificationField;
        }
        set {
            this.organizationOtherIdentificationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://niem.gov/niem/niem-core/2.0")]
[System.Xml.Serialization.XmlRootAttribute("Identification", Namespace="http://niem.gov/niem/niem-core/2.0", IsNullable=true)]
public partial class IdentificationType : ComplexObjectType {
    
    private @string identificationIDField;
    
    private object identificationCategoryField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public @string IdentificationID {
        get {
            return this.identificationIDField;
        }
        set {
            this.identificationIDField = value;
        }
    }
    
    /// <remarks/>
    public object IdentificationCategory {
        get {
            return this.identificationCategoryField;
        }
        set {
            this.identificationCategoryField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(BinaryType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(DocumentType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(DocumentType1))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ObligationExemptionType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ObligationExemptionType1))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(PaymentElectronicBankDraftType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ObligationType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ObligationType1))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ActivityType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(CaseType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(CaseType1))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(AssociationType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(PersonContactInformationAssociationType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(OrganizationContactInformationAssociationType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityDocumentAssociationType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityCaseAssociationType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(NANPTelephoneNumberType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(TelephoneNumberType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(StreetType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(StructuredAddressType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(AddressType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ContactInformationType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(OrganizationType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(CourtType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(IdentificationType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(PersonNameType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(DateType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(PersonType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(MoEcfExchangeType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://niem.gov/niem/structures/2.0")]
public abstract partial class ComplexObjectType {
    
    private string idField;
    
    private string metadataField;
    
    private string linkMetadataField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="ID")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="IDREFS")]
    public string metadata {
        get {
            return this.metadataField;
        }
        set {
            this.metadataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="IDREFS")]
    public string linkMetadata {
        get {
            return this.linkMetadataField;
        }
        set {
            this.linkMetadataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://niem.gov/niem/niem-core/2.0")]
public partial class EntityType : ComplexObjectType {
    
    private object[] entityRepresentationField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("EntityRepresentation")]
    public object[] EntityRepresentation {
        get {
            return this.entityRepresentationField;
        }
        set {
            this.entityRepresentationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://niem.gov/niem/niem-core/2.0")]
[System.Xml.Serialization.XmlRootAttribute("DocumentBinary", Namespace="http://niem.gov/niem/niem-core/2.0", IsNullable=true)]
public partial class BinaryType : ComplexObjectType {
    
    private base64Binary itemField;
    
    private @string binaryFormatIDField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("BinaryBase64Object", IsNullable=true)]
    public base64Binary Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public @string BinaryFormatID {
        get {
            return this.binaryFormatIDField;
        }
        set {
            this.binaryFormatIDField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(DocumentType1))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://niem.gov/niem/niem-core/2.0")]
[System.Xml.Serialization.XmlRootAttribute("Document", Namespace="http://niem.gov/niem/niem-core/2.0", IsNullable=true)]
public partial class DocumentType : ComplexObjectType {
    
    private BinaryType documentBinaryField;
    
    private TextType documentTitleTextField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public BinaryType DocumentBinary {
        get {
            return this.documentBinaryField;
        }
        set {
            this.documentBinaryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public TextType DocumentTitleText {
        get {
            return this.documentTitleTextField;
        }
        set {
            this.documentTitleTextField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="DocumentType", Namespace="http://www.courts.mo.gov/exchanges/MoEcfExchangeExtensions/1.0")]
[System.Xml.Serialization.XmlRootAttribute("PrimaryDocument", Namespace="http://www.courts.mo.gov/exchanges/MoEcfExchangeExtensions/1.0", IsNullable=false)]
public partial class DocumentType1 : DocumentType {
    
    private TextType documentCategoryTextField;
    
    private DocumentType[] documentField;
    
    private TextType[] documentRespondToSequenceTextField;
    
    /// <remarks/>
    public TextType DocumentCategoryText {
        get {
            return this.documentCategoryTextField;
        }
        set {
            this.documentCategoryTextField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Document", Namespace="http://niem.gov/niem/niem-core/2.0", IsNullable=true)]
    public DocumentType[] Document {
        get {
            return this.documentField;
        }
        set {
            this.documentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DocumentRespondToSequenceText")]
    public TextType[] DocumentRespondToSequenceText {
        get {
            return this.documentRespondToSequenceTextField;
        }
        set {
            this.documentRespondToSequenceTextField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ObligationExemptionType1))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://niem.gov/niem/niem-core/2.0")]
public partial class ObligationExemptionType : ComplexObjectType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="ObligationExemptionType", Namespace="http://www.courts.mo.gov/exchanges/MoEcfExchangeExtensions/1.0")]
[System.Xml.Serialization.XmlRootAttribute("ObligationExemption", Namespace="http://www.courts.mo.gov/exchanges/MoEcfExchangeExtensions/1.0", IsNullable=false)]
public partial class ObligationExemptionType1 : ObligationExemptionType {
    
    private ObligationExemptionCodeType obligationExemptionCodeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.courts.mo.gov/exchanges/MoEcfExchange/1.0", IsNullable=true)]
    public ObligationExemptionCodeType ObligationExemptionCode {
        get {
            return this.obligationExemptionCodeField;
        }
        set {
            this.obligationExemptionCodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.courts.mo.gov/exchanges/MoEcfExchange/1.0")]
[System.Xml.Serialization.XmlRootAttribute("ObligationExemptionCode", Namespace="http://www.courts.mo.gov/exchanges/MoEcfExchange/1.0", IsNullable=true)]
public partial class ObligationExemptionCodeType {
    
    private string idField;
    
    private string metadataField;
    
    private string linkMetadataField;
    
    private ObligationExemptionCodeSimpleType valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://niem.gov/niem/structures/2.0", DataType="ID")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://niem.gov/niem/structures/2.0", DataType="IDREFS")]
    public string metadata {
        get {
            return this.metadataField;
        }
        set {
            this.metadataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://niem.gov/niem/structures/2.0", DataType="IDREFS")]
    public string linkMetadata {
        get {
            return this.linkMetadataField;
        }
        set {
            this.linkMetadataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public ObligationExemptionCodeSimpleType Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.courts.mo.gov/exchanges/MoEcfExchange/1.0")]
public enum ObligationExemptionCodeSimpleType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("514")]
    Item514,
    
    /// <remarks/>
    GOVATTY,
    
    /// <remarks/>
    IFP,
    
    /// <remarks/>
    OTHER,
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ObligationType1))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://niem.gov/niem/niem-core/2.0")]
[System.Xml.Serialization.XmlRootAttribute("Fee", Namespace="http://niem.gov/niem/niem-core/2.0", IsNullable=true)]
public partial class ObligationType : ComplexObjectType {
    
    private AmountType itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ObligationDueAmount", IsNullable=true)]
    public AmountType Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="ObligationType", Namespace="http://www.courts.mo.gov/exchanges/MoEcfExchangeExtensions/1.0")]
[System.Xml.Serialization.XmlRootAttribute("Fee", Namespace="http://www.courts.mo.gov/exchanges/MoEcfExchangeExtensions/1.0", IsNullable=false)]
public partial class ObligationType1 : ObligationType {
    
    private object item1Field;
    
    private ObligationExemptionType1[] obligationExemptionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PaymentCourtDebitAccount", typeof(@string), Namespace="http://www.courts.mo.gov/exchanges/MoEcfExchange/1.0", IsNullable=true)]
    [System.Xml.Serialization.XmlElementAttribute("PaymentElectronicBankDraft", typeof(PaymentElectronicBankDraftType), Namespace="http://www.courts.mo.gov/exchanges/MoEcfExchange/1.0", IsNullable=true)]
    public object Item1 {
        get {
            return this.item1Field;
        }
        set {
            this.item1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ObligationExemption")]
    public ObligationExemptionType1[] ObligationExemption {
        get {
            return this.obligationExemptionField;
        }
        set {
            this.obligationExemptionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.courts.mo.gov/exchanges/MoEcfExchange/1.0")]
[System.Xml.Serialization.XmlRootAttribute("PaymentElectronicBankDraft", Namespace="http://www.courts.mo.gov/exchanges/MoEcfExchange/1.0", IsNullable=true)]
public partial class PaymentElectronicBankDraftType : ComplexObjectType {
    
    private BankAccountCategoryCodeType bankAccountCategoryCodeField;
    
    private CheckCategoryCodeType checkCategoryCodeField;
    
    private @string routingNumberField;
    
    private @string accountNumberField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public BankAccountCategoryCodeType BankAccountCategoryCode {
        get {
            return this.bankAccountCategoryCodeField;
        }
        set {
            this.bankAccountCategoryCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public CheckCategoryCodeType CheckCategoryCode {
        get {
            return this.checkCategoryCodeField;
        }
        set {
            this.checkCategoryCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public @string RoutingNumber {
        get {
            return this.routingNumberField;
        }
        set {
            this.routingNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public @string AccountNumber {
        get {
            return this.accountNumberField;
        }
        set {
            this.accountNumberField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.courts.mo.gov/exchanges/MoEcfExchange/1.0")]
[System.Xml.Serialization.XmlRootAttribute("BankAccountCategoryCode", Namespace="http://www.courts.mo.gov/exchanges/MoEcfExchange/1.0", IsNullable=true)]
public partial class BankAccountCategoryCodeType {
    
    private string idField;
    
    private string metadataField;
    
    private string linkMetadataField;
    
    private BankAccountCategoryCodeSimpleType valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://niem.gov/niem/structures/2.0", DataType="ID")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://niem.gov/niem/structures/2.0", DataType="IDREFS")]
    public string metadata {
        get {
            return this.metadataField;
        }
        set {
            this.metadataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://niem.gov/niem/structures/2.0", DataType="IDREFS")]
    public string linkMetadata {
        get {
            return this.linkMetadataField;
        }
        set {
            this.linkMetadataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public BankAccountCategoryCodeSimpleType Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.courts.mo.gov/exchanges/MoEcfExchange/1.0")]
public enum BankAccountCategoryCodeSimpleType {
    
    /// <remarks/>
    C,
    
    /// <remarks/>
    S,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.courts.mo.gov/exchanges/MoEcfExchange/1.0")]
[System.Xml.Serialization.XmlRootAttribute("CheckCategoryCode", Namespace="http://www.courts.mo.gov/exchanges/MoEcfExchange/1.0", IsNullable=true)]
public partial class CheckCategoryCodeType {
    
    private string idField;
    
    private string metadataField;
    
    private string linkMetadataField;
    
    private CheckCategoryCodeSimpleType valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://niem.gov/niem/structures/2.0", DataType="ID")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://niem.gov/niem/structures/2.0", DataType="IDREFS")]
    public string metadata {
        get {
            return this.metadataField;
        }
        set {
            this.metadataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://niem.gov/niem/structures/2.0", DataType="IDREFS")]
    public string linkMetadata {
        get {
            return this.linkMetadataField;
        }
        set {
            this.linkMetadataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public CheckCategoryCodeSimpleType Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.courts.mo.gov/exchanges/MoEcfExchange/1.0")]
public enum CheckCategoryCodeSimpleType {
    
    /// <remarks/>
    B,
    
    /// <remarks/>
    P,
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(CaseType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(CaseType1))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://niem.gov/niem/niem-core/2.0")]
public partial class ActivityType : ComplexObjectType {
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(CaseType1))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://niem.gov/niem/niem-core/2.0")]
[System.Xml.Serialization.XmlRootAttribute("Case", Namespace="http://niem.gov/niem/niem-core/2.0", IsNullable=true)]
public partial class CaseType : ActivityType {
    
    private TextType caseTitleTextField;
    
    private TextType caseCategoryTextField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public TextType CaseTitleText {
        get {
            return this.caseTitleTextField;
        }
        set {
            this.caseTitleTextField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public TextType CaseCategoryText {
        get {
            return this.caseCategoryTextField;
        }
        set {
            this.caseCategoryTextField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="CaseType", Namespace="http://niem.gov/niem/domains/jxdm/4.1")]
[System.Xml.Serialization.XmlRootAttribute("Case", Namespace="http://niem.gov/niem/domains/jxdm/4.1", IsNullable=true)]
public partial class CaseType1 : CaseType {
    
    private CaseAugmentationType caseAugmentationField;
    
    /// <remarks/>
    public CaseAugmentationType CaseAugmentation {
        get {
            return this.caseAugmentationField;
        }
        set {
            this.caseAugmentationField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(PersonContactInformationAssociationType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(OrganizationContactInformationAssociationType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityDocumentAssociationType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityCaseAssociationType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://niem.gov/niem/niem-core/2.0")]
public partial class AssociationType : ComplexObjectType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://niem.gov/niem/niem-core/2.0")]
[System.Xml.Serialization.XmlRootAttribute("PersonContactInformationAssociation", Namespace="http://niem.gov/niem/niem-core/2.0", IsNullable=true)]
public partial class PersonContactInformationAssociationType : AssociationType {
    
    private ReferenceType personReferenceField;
    
    private ReferenceType contactInformationReferenceField;
    
    /// <remarks/>
    public ReferenceType PersonReference {
        get {
            return this.personReferenceField;
        }
        set {
            this.personReferenceField = value;
        }
    }
    
    /// <remarks/>
    public ReferenceType ContactInformationReference {
        get {
            return this.contactInformationReferenceField;
        }
        set {
            this.contactInformationReferenceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://niem.gov/niem/structures/2.0")]
[System.Xml.Serialization.XmlRootAttribute("EntityPersonReference", Namespace="http://www.courts.mo.gov/exchanges/MoEcfExchange/1.0", IsNullable=false)]
public partial class ReferenceType {
    
    private string idField;
    
    private string refField;
    
    private string linkMetadataField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="ID")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="IDREF")]
    public string @ref {
        get {
            return this.refField;
        }
        set {
            this.refField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="IDREFS")]
    public string linkMetadata {
        get {
            return this.linkMetadataField;
        }
        set {
            this.linkMetadataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://niem.gov/niem/niem-core/2.0")]
[System.Xml.Serialization.XmlRootAttribute("OrganizationContactInformationAssociation", Namespace="http://niem.gov/niem/niem-core/2.0", IsNullable=true)]
public partial class OrganizationContactInformationAssociationType : AssociationType {
    
    private ReferenceType organizationReferenceField;
    
    private ReferenceType contactInformationReferenceField;
    
    /// <remarks/>
    public ReferenceType OrganizationReference {
        get {
            return this.organizationReferenceField;
        }
        set {
            this.organizationReferenceField = value;
        }
    }
    
    /// <remarks/>
    public ReferenceType ContactInformationReference {
        get {
            return this.contactInformationReferenceField;
        }
        set {
            this.contactInformationReferenceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.courts.mo.gov/exchanges/MoEcfExchangeExtensions/1.0")]
[System.Xml.Serialization.XmlRootAttribute("EntityDocumentAssociation", Namespace="http://www.courts.mo.gov/exchanges/MoEcfExchangeExtensions/1.0", IsNullable=false)]
public partial class EntityDocumentAssociationType : AssociationType {
    
    private ReferenceType documentReferenceField;
    
    private object entityRepresentationField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://niem.gov/niem/niem-core/2.0")]
    public ReferenceType DocumentReference {
        get {
            return this.documentReferenceField;
        }
        set {
            this.documentReferenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://niem.gov/niem/niem-core/2.0")]
    public object EntityRepresentation {
        get {
            return this.entityRepresentationField;
        }
        set {
            this.entityRepresentationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.courts.mo.gov/exchanges/MoEcfExchangeExtensions/1.0")]
[System.Xml.Serialization.XmlRootAttribute("EntityCaseAssociation", Namespace="http://www.courts.mo.gov/exchanges/MoEcfExchangeExtensions/1.0", IsNullable=false)]
public partial class EntityCaseAssociationType : AssociationType {
    
    private ReferenceType caseReferenceField;
    
    private object entityRepresentationField;
    
    private TextType associationDescriptionTextField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://niem.gov/niem/niem-core/2.0")]
    public ReferenceType CaseReference {
        get {
            return this.caseReferenceField;
        }
        set {
            this.caseReferenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://niem.gov/niem/niem-core/2.0")]
    public object EntityRepresentation {
        get {
            return this.entityRepresentationField;
        }
        set {
            this.entityRepresentationField = value;
        }
    }
    
    /// <remarks/>
    public TextType AssociationDescriptionText {
        get {
            return this.associationDescriptionTextField;
        }
        set {
            this.associationDescriptionTextField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://niem.gov/niem/niem-core/2.0")]
[System.Xml.Serialization.XmlRootAttribute("NANPTelephoneNumber", Namespace="http://niem.gov/niem/niem-core/2.0", IsNullable=true)]
public partial class NANPTelephoneNumberType : ComplexObjectType {
    
    private @string telephoneAreaCodeIDField;
    
    private @string telephoneExchangeIDField;
    
    private @string telephoneLineIDField;
    
    private @string telephoneSuffixIDField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public @string TelephoneAreaCodeID {
        get {
            return this.telephoneAreaCodeIDField;
        }
        set {
            this.telephoneAreaCodeIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public @string TelephoneExchangeID {
        get {
            return this.telephoneExchangeIDField;
        }
        set {
            this.telephoneExchangeIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public @string TelephoneLineID {
        get {
            return this.telephoneLineIDField;
        }
        set {
            this.telephoneLineIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public @string TelephoneSuffixID {
        get {
            return this.telephoneSuffixIDField;
        }
        set {
            this.telephoneSuffixIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://niem.gov/niem/niem-core/2.0")]
[System.Xml.Serialization.XmlRootAttribute("ContactTelephoneNumber", Namespace="http://niem.gov/niem/niem-core/2.0", IsNullable=true)]
public partial class TelephoneNumberType : ComplexObjectType {
    
    private NANPTelephoneNumberType itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("NANPTelephoneNumber", IsNullable=true)]
    public NANPTelephoneNumberType Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://niem.gov/niem/niem-core/2.0")]
[System.Xml.Serialization.XmlRootAttribute("LocationStreet", Namespace="http://niem.gov/niem/niem-core/2.0", IsNullable=true)]
public partial class StreetType : ComplexObjectType {
    
    private TextType streetFullTextField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public TextType StreetFullText {
        get {
            return this.streetFullTextField;
        }
        set {
            this.streetFullTextField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://niem.gov/niem/niem-core/2.0")]
[System.Xml.Serialization.XmlRootAttribute("StructuredAddress", Namespace="http://niem.gov/niem/niem-core/2.0", IsNullable=true)]
public partial class StructuredAddressType : ComplexObjectType {
    
    private StreetType[] itemsField;
    
    private ProperNameTextType locationCityNameField;
    
    private object itemField;
    
    private CountryAlpha2CodeType item1Field;
    
    private @string locationPostalCodeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("LocationStreet", IsNullable=true)]
    public StreetType[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public ProperNameTextType LocationCityName {
        get {
            return this.locationCityNameField;
        }
        set {
            this.locationCityNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("LocationStateName", typeof(ProperNameTextType), IsNullable=true)]
    [System.Xml.Serialization.XmlElementAttribute("LocationStateUSPostalServiceCode", typeof(USStateCodeType), IsNullable=true)]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("LocationCountryISO3166Alpha2Code", IsNullable=true)]
    public CountryAlpha2CodeType Item1 {
        get {
            return this.item1Field;
        }
        set {
            this.item1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public @string LocationPostalCode {
        get {
            return this.locationPostalCodeField;
        }
        set {
            this.locationPostalCodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://niem.gov/niem/niem-core/2.0")]
[System.Xml.Serialization.XmlRootAttribute("ContactMailingAddress", Namespace="http://niem.gov/niem/niem-core/2.0", IsNullable=true)]
public partial class AddressType : ComplexObjectType {
    
    private StructuredAddressType itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("StructuredAddress", IsNullable=true)]
    public StructuredAddressType Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://niem.gov/niem/niem-core/2.0")]
[System.Xml.Serialization.XmlRootAttribute("ContactInformation", Namespace="http://niem.gov/niem/niem-core/2.0", IsNullable=true)]
public partial class ContactInformationType : ComplexObjectType {
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ContactEmailID", typeof(@string), IsNullable=true)]
    [System.Xml.Serialization.XmlElementAttribute("ContactMailingAddress", typeof(AddressType), IsNullable=true)]
    [System.Xml.Serialization.XmlElementAttribute("ContactTelephoneNumber", typeof(TelephoneNumberType), IsNullable=true)]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://niem.gov/niem/niem-core/2.0")]
[System.Xml.Serialization.XmlRootAttribute("PersonName", Namespace="http://niem.gov/niem/niem-core/2.0", IsNullable=true)]
public partial class PersonNameType : ComplexObjectType {
    
    private PersonNameTextType personGivenNameField;
    
    private PersonNameTextType personMiddleNameField;
    
    private PersonNameTextType personSurNameField;
    
    private TextType personNameSuffixTextField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public PersonNameTextType PersonGivenName {
        get {
            return this.personGivenNameField;
        }
        set {
            this.personGivenNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public PersonNameTextType PersonMiddleName {
        get {
            return this.personMiddleNameField;
        }
        set {
            this.personMiddleNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public PersonNameTextType PersonSurName {
        get {
            return this.personSurNameField;
        }
        set {
            this.personSurNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public TextType PersonNameSuffixText {
        get {
            return this.personNameSuffixTextField;
        }
        set {
            this.personNameSuffixTextField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.courts.mo.gov/exchanges/MoEcfExchange/1.0")]
[System.Xml.Serialization.XmlRootAttribute("IdentificationCategoryCode", Namespace="http://www.courts.mo.gov/exchanges/MoEcfExchange/1.0", IsNullable=true)]
public partial class IdentificationCategoryCodeType {
    
    private string idField;
    
    private string metadataField;
    
    private string linkMetadataField;
    
    private IdentificationCategoryCodeSimpleType valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://niem.gov/niem/structures/2.0", DataType="ID")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://niem.gov/niem/structures/2.0", DataType="IDREFS")]
    public string metadata {
        get {
            return this.metadataField;
        }
        set {
            this.metadataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://niem.gov/niem/structures/2.0", DataType="IDREFS")]
    public string linkMetadata {
        get {
            return this.linkMetadataField;
        }
        set {
            this.linkMetadataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public IdentificationCategoryCodeSimpleType Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.courts.mo.gov/exchanges/MoEcfExchange/1.0")]
public enum IdentificationCategoryCodeSimpleType {
    
    /// <remarks/>
    PIDM,
    
    /// <remarks/>
    SPRIDEN,
    
    /// <remarks/>
    EIN,
    
    /// <remarks/>
    SSN,
    
    /// <remarks/>
    CONFNO,
    
    /// <remarks/>
    CASENO,
    
    /// <remarks/>
    USERNAME,
    
    /// <remarks/>
    ATTYREFNO,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://niem.gov/niem/appinfo/2.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://niem.gov/niem/appinfo/2.0", IsNullable=false)]
public partial class Resource {
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="NCName")]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://niem.gov/niem/appinfo/2.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://niem.gov/niem/appinfo/2.0", IsNullable=false)]
public partial class Deprecated {
    
    private bool valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
    public bool value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://niem.gov/niem/appinfo/2.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://niem.gov/niem/appinfo/2.0", IsNullable=false)]
public partial class Base {
    
    private string nameField;
    
    private string namespaceField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="NCName")]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="anyURI")]
    public string @namespace {
        get {
            return this.namespaceField;
        }
        set {
            this.namespaceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://niem.gov/niem/appinfo/2.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://niem.gov/niem/appinfo/2.0", IsNullable=false)]
public partial class ReferenceTarget {
    
    private string nameField;
    
    private string namespaceField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="NCName")]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="anyURI")]
    public string @namespace {
        get {
            return this.namespaceField;
        }
        set {
            this.namespaceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://niem.gov/niem/appinfo/2.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://niem.gov/niem/appinfo/2.0", IsNullable=false)]
public partial class AppliesTo {
    
    private string nameField;
    
    private string namespaceField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="NCName")]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="anyURI")]
    public string @namespace {
        get {
            return this.namespaceField;
        }
        set {
            this.namespaceField = value;
        }
    }
}
