//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoCourtDocumentUpload.MoExchangeServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.courts.mo.gov/exchanges/moecfaf/1.0", ConfigurationName="MoExchangeServiceReference.FilingServicePortType")]
    public interface FilingServicePortType {
        
        // CODEGEN: Generating message contract since message part namespace (http://www.courts.mo.gov/exchanges/ExchangeDocument/1.0) does not match the default value (http://www.courts.mo.gov/exchanges/moecfaf/1.0)
        [System.ServiceModel.OperationContractAttribute(Action="urn:fileNewCase", ReplyAction="urn:fileNewCaseResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MoExchangeRequestType))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="MoExchangeResponse")]
        MoCourtDocumentUpload.MoExchangeServiceReference.fileNewCaseResponse fileNewCase(MoCourtDocumentUpload.MoExchangeServiceReference.fileNewCaseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:fileNewCase", ReplyAction="urn:fileNewCaseResponse")]
        System.Threading.Tasks.Task<MoCourtDocumentUpload.MoExchangeServiceReference.fileNewCaseResponse> fileNewCaseAsync(MoCourtDocumentUpload.MoExchangeServiceReference.fileNewCaseRequest request);
        
        // CODEGEN: Generating message contract since message part namespace (http://www.courts.mo.gov/exchanges/ExchangeDocument/1.0) does not match the default value (http://www.courts.mo.gov/exchanges/moecfaf/1.0)
        [System.ServiceModel.OperationContractAttribute(Action="urn:fileOnExistingCase", ReplyAction="urn:fileOnExistingCaseResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MoExchangeRequestType))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="MoExchangeResponse")]
        MoCourtDocumentUpload.MoExchangeServiceReference.fileOnExistingCaseResponse fileOnExistingCase(MoCourtDocumentUpload.MoExchangeServiceReference.fileOnExistingCaseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:fileOnExistingCase", ReplyAction="urn:fileOnExistingCaseResponse")]
        System.Threading.Tasks.Task<MoCourtDocumentUpload.MoExchangeServiceReference.fileOnExistingCaseResponse> fileOnExistingCaseAsync(MoCourtDocumentUpload.MoExchangeServiceReference.fileOnExistingCaseRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.courts.mo.gov/exchanges/ExchangeDocument/1.0")]
    public partial class MoExchangeRequestPayloadType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private MoExchangeHeaderType moExchangeHeaderField;
        
        private MoExchangeStructuredDataPayloadType moExchangeStructuredDataPayloadField;
        
        private MoExchangeNotificationType moExchangeNotificationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MoExchangeHeaderType MoExchangeHeader {
            get {
                return this.moExchangeHeaderField;
            }
            set {
                this.moExchangeHeaderField = value;
                this.RaisePropertyChanged("MoExchangeHeader");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public MoExchangeStructuredDataPayloadType MoExchangeStructuredDataPayload {
            get {
                return this.moExchangeStructuredDataPayloadField;
            }
            set {
                this.moExchangeStructuredDataPayloadField = value;
                this.RaisePropertyChanged("MoExchangeStructuredDataPayload");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public MoExchangeNotificationType MoExchangeNotification {
            get {
                return this.moExchangeNotificationField;
            }
            set {
                this.moExchangeNotificationField = value;
                this.RaisePropertyChanged("MoExchangeNotification");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.courts.mo.gov/exchanges/ExchangeDocument/1.0")]
    public partial class MoExchangeHeaderType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string headerVersionField;
        
        private string serviceNameField;
        
        private string serviceVersionField;
        
        private string transactionNameField;
        
        private string transactionTypeField;
        
        private string messageIDField;
        
        private string messagePriorityField;
        
        private string messageTypeField;
        
        private string requestOriginatorField;
        
        private string sourceLogicalNameField;
        
        private string destinationLogicalNameField;
        
        private string notificationDestinationsField;
        
        private string sourceORIField;
        
        private string destinationORIField;
        
        private string payloadFormatField;
        
        private string futurePathField;
        
        private string delayedResponsePathField;
        
        private string pastPathField;
        
        private string logLevelField;
        
        private string errorIDField;
        
        private string userIDField;
        
        private System.DateTime creationTimestampField;
        
        private bool creationTimestampFieldSpecified;
        
        private string expiryPeriodField;
        
        private string confidentialityFlagField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string HeaderVersion {
            get {
                return this.headerVersionField;
            }
            set {
                this.headerVersionField = value;
                this.RaisePropertyChanged("HeaderVersion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ServiceName {
            get {
                return this.serviceNameField;
            }
            set {
                this.serviceNameField = value;
                this.RaisePropertyChanged("ServiceName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ServiceVersion {
            get {
                return this.serviceVersionField;
            }
            set {
                this.serviceVersionField = value;
                this.RaisePropertyChanged("ServiceVersion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string TransactionName {
            get {
                return this.transactionNameField;
            }
            set {
                this.transactionNameField = value;
                this.RaisePropertyChanged("TransactionName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string TransactionType {
            get {
                return this.transactionTypeField;
            }
            set {
                this.transactionTypeField = value;
                this.RaisePropertyChanged("TransactionType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string MessageID {
            get {
                return this.messageIDField;
            }
            set {
                this.messageIDField = value;
                this.RaisePropertyChanged("MessageID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string MessagePriority {
            get {
                return this.messagePriorityField;
            }
            set {
                this.messagePriorityField = value;
                this.RaisePropertyChanged("MessagePriority");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string MessageType {
            get {
                return this.messageTypeField;
            }
            set {
                this.messageTypeField = value;
                this.RaisePropertyChanged("MessageType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string RequestOriginator {
            get {
                return this.requestOriginatorField;
            }
            set {
                this.requestOriginatorField = value;
                this.RaisePropertyChanged("RequestOriginator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string SourceLogicalName {
            get {
                return this.sourceLogicalNameField;
            }
            set {
                this.sourceLogicalNameField = value;
                this.RaisePropertyChanged("SourceLogicalName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string DestinationLogicalName {
            get {
                return this.destinationLogicalNameField;
            }
            set {
                this.destinationLogicalNameField = value;
                this.RaisePropertyChanged("DestinationLogicalName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string NotificationDestinations {
            get {
                return this.notificationDestinationsField;
            }
            set {
                this.notificationDestinationsField = value;
                this.RaisePropertyChanged("NotificationDestinations");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string SourceORI {
            get {
                return this.sourceORIField;
            }
            set {
                this.sourceORIField = value;
                this.RaisePropertyChanged("SourceORI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string DestinationORI {
            get {
                return this.destinationORIField;
            }
            set {
                this.destinationORIField = value;
                this.RaisePropertyChanged("DestinationORI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string PayloadFormat {
            get {
                return this.payloadFormatField;
            }
            set {
                this.payloadFormatField = value;
                this.RaisePropertyChanged("PayloadFormat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string FuturePath {
            get {
                return this.futurePathField;
            }
            set {
                this.futurePathField = value;
                this.RaisePropertyChanged("FuturePath");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string DelayedResponsePath {
            get {
                return this.delayedResponsePathField;
            }
            set {
                this.delayedResponsePathField = value;
                this.RaisePropertyChanged("DelayedResponsePath");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string PastPath {
            get {
                return this.pastPathField;
            }
            set {
                this.pastPathField = value;
                this.RaisePropertyChanged("PastPath");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string LogLevel {
            get {
                return this.logLevelField;
            }
            set {
                this.logLevelField = value;
                this.RaisePropertyChanged("LogLevel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string ErrorID {
            get {
                return this.errorIDField;
            }
            set {
                this.errorIDField = value;
                this.RaisePropertyChanged("ErrorID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
                this.RaisePropertyChanged("UserID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public System.DateTime CreationTimestamp {
            get {
                return this.creationTimestampField;
            }
            set {
                this.creationTimestampField = value;
                this.RaisePropertyChanged("CreationTimestamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CreationTimestampSpecified {
            get {
                return this.creationTimestampFieldSpecified;
            }
            set {
                this.creationTimestampFieldSpecified = value;
                this.RaisePropertyChanged("CreationTimestampSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string ExpiryPeriod {
            get {
                return this.expiryPeriodField;
            }
            set {
                this.expiryPeriodField = value;
                this.RaisePropertyChanged("ExpiryPeriod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string ConfidentialityFlag {
            get {
                return this.confidentialityFlagField;
            }
            set {
                this.confidentialityFlagField = value;
                this.RaisePropertyChanged("ConfidentialityFlag");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.courts.mo.gov/exchanges/ExchangeDocument/1.0")]
    public partial class MoExchangeRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private MoExchangeRequestPayloadType moExchangeRequestField;
        
        private MoExchangeNotificationType moExchangeNotificationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MoExchangeRequestPayloadType MoExchangeRequest {
            get {
                return this.moExchangeRequestField;
            }
            set {
                this.moExchangeRequestField = value;
                this.RaisePropertyChanged("MoExchangeRequest");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public MoExchangeNotificationType MoExchangeNotification {
            get {
                return this.moExchangeNotificationField;
            }
            set {
                this.moExchangeNotificationField = value;
                this.RaisePropertyChanged("MoExchangeNotification");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.courts.mo.gov/exchanges/ExchangeDocument/1.0")]
    public partial class MoExchangeNotificationType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageIDField;
        
        private string sourceField;
        
        private string destinationField;
        
        private string priorityField;
        
        private string deliveryAgentField;
        
        private string notificationMessageField;
        
        private DeliveryAgentHeaderType deliveryAgentHeaderField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MessageID {
            get {
                return this.messageIDField;
            }
            set {
                this.messageIDField = value;
                this.RaisePropertyChanged("MessageID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
                this.RaisePropertyChanged("Source");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
                this.RaisePropertyChanged("Destination");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Priority {
            get {
                return this.priorityField;
            }
            set {
                this.priorityField = value;
                this.RaisePropertyChanged("Priority");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string DeliveryAgent {
            get {
                return this.deliveryAgentField;
            }
            set {
                this.deliveryAgentField = value;
                this.RaisePropertyChanged("DeliveryAgent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string NotificationMessage {
            get {
                return this.notificationMessageField;
            }
            set {
                this.notificationMessageField = value;
                this.RaisePropertyChanged("NotificationMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public DeliveryAgentHeaderType DeliveryAgentHeader {
            get {
                return this.deliveryAgentHeaderField;
            }
            set {
                this.deliveryAgentHeaderField = value;
                this.RaisePropertyChanged("DeliveryAgentHeader");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.courts.mo.gov/exchanges/ExchangeDocument/1.0")]
    public partial class DeliveryAgentHeaderType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private DeliveryAgentHeaderTypeWebServiceDeliveryAgent webServiceDeliveryAgentField;
        
        private DeliveryAgentHeaderTypeMQDeliveryAgent mQDeliveryAgentField;
        
        private DeliveryAgentHeaderTypeEmailDeliveryAgent emailDeliveryAgentField;
        
        private DeliveryAgentHeaderTypePagerDeliveryAgent pagerDeliveryAgentField;
        
        private DeliveryAgentHeaderTypeFTPDeliveryAgent fTPDeliveryAgentField;
        
        private DeliveryAgentHeaderTypeDatabaseDeliveryAgent databaseDeliveryAgentField;
        
        private DeliveryAgentHeaderTypePrinterDeliveryAgent printerDeliveryAgentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public DeliveryAgentHeaderTypeWebServiceDeliveryAgent WebServiceDeliveryAgent {
            get {
                return this.webServiceDeliveryAgentField;
            }
            set {
                this.webServiceDeliveryAgentField = value;
                this.RaisePropertyChanged("WebServiceDeliveryAgent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public DeliveryAgentHeaderTypeMQDeliveryAgent MQDeliveryAgent {
            get {
                return this.mQDeliveryAgentField;
            }
            set {
                this.mQDeliveryAgentField = value;
                this.RaisePropertyChanged("MQDeliveryAgent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public DeliveryAgentHeaderTypeEmailDeliveryAgent EmailDeliveryAgent {
            get {
                return this.emailDeliveryAgentField;
            }
            set {
                this.emailDeliveryAgentField = value;
                this.RaisePropertyChanged("EmailDeliveryAgent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public DeliveryAgentHeaderTypePagerDeliveryAgent PagerDeliveryAgent {
            get {
                return this.pagerDeliveryAgentField;
            }
            set {
                this.pagerDeliveryAgentField = value;
                this.RaisePropertyChanged("PagerDeliveryAgent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public DeliveryAgentHeaderTypeFTPDeliveryAgent FTPDeliveryAgent {
            get {
                return this.fTPDeliveryAgentField;
            }
            set {
                this.fTPDeliveryAgentField = value;
                this.RaisePropertyChanged("FTPDeliveryAgent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public DeliveryAgentHeaderTypeDatabaseDeliveryAgent DatabaseDeliveryAgent {
            get {
                return this.databaseDeliveryAgentField;
            }
            set {
                this.databaseDeliveryAgentField = value;
                this.RaisePropertyChanged("DatabaseDeliveryAgent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public DeliveryAgentHeaderTypePrinterDeliveryAgent PrinterDeliveryAgent {
            get {
                return this.printerDeliveryAgentField;
            }
            set {
                this.printerDeliveryAgentField = value;
                this.RaisePropertyChanged("PrinterDeliveryAgent");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.courts.mo.gov/exchanges/ExchangeDocument/1.0")]
    public partial class DeliveryAgentHeaderTypeWebServiceDeliveryAgent : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string webServiceTypeField;
        
        private string webServiceEndPointField;
        
        private string webServiceOperationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string WebServiceType {
            get {
                return this.webServiceTypeField;
            }
            set {
                this.webServiceTypeField = value;
                this.RaisePropertyChanged("WebServiceType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string WebServiceEndPoint {
            get {
                return this.webServiceEndPointField;
            }
            set {
                this.webServiceEndPointField = value;
                this.RaisePropertyChanged("WebServiceEndPoint");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string WebServiceOperation {
            get {
                return this.webServiceOperationField;
            }
            set {
                this.webServiceOperationField = value;
                this.RaisePropertyChanged("WebServiceOperation");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.courts.mo.gov/exchanges/ExchangeDocument/1.0")]
    public partial class DeliveryAgentHeaderTypeMQDeliveryAgent : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string queueManagerField;
        
        private string queueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string QueueManager {
            get {
                return this.queueManagerField;
            }
            set {
                this.queueManagerField = value;
                this.RaisePropertyChanged("QueueManager");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Queue {
            get {
                return this.queueField;
            }
            set {
                this.queueField = value;
                this.RaisePropertyChanged("Queue");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.courts.mo.gov/exchanges/ExchangeDocument/1.0")]
    public partial class DeliveryAgentHeaderTypeEmailDeliveryAgent : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string toEmailIDField;
        
        private string fromEmailIDField;
        
        private string subjectField;
        
        private AttachmentType[] attachmentsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ToEmailID {
            get {
                return this.toEmailIDField;
            }
            set {
                this.toEmailIDField = value;
                this.RaisePropertyChanged("ToEmailID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FromEmailID {
            get {
                return this.fromEmailIDField;
            }
            set {
                this.fromEmailIDField = value;
                this.RaisePropertyChanged("FromEmailID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
                this.RaisePropertyChanged("Subject");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Attachment", IsNullable=false)]
        public AttachmentType[] Attachments {
            get {
                return this.attachmentsField;
            }
            set {
                this.attachmentsField = value;
                this.RaisePropertyChanged("Attachments");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.courts.mo.gov/exchanges/ExchangeDocument/1.0")]
    public partial class AttachmentType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mIMETypeField;
        
        private string fileNameField;
        
        private string dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MIMEType {
            get {
                return this.mIMETypeField;
            }
            set {
                this.mIMETypeField = value;
                this.RaisePropertyChanged("MIMEType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
                this.RaisePropertyChanged("FileName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("Data");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.courts.mo.gov/exchanges/ExchangeDocument/1.0")]
    public partial class DeliveryAgentHeaderTypePagerDeliveryAgent : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string pagerNumberField;
        
        private string senderNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string PagerNumber {
            get {
                return this.pagerNumberField;
            }
            set {
                this.pagerNumberField = value;
                this.RaisePropertyChanged("PagerNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SenderName {
            get {
                return this.senderNameField;
            }
            set {
                this.senderNameField = value;
                this.RaisePropertyChanged("SenderName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.courts.mo.gov/exchanges/ExchangeDocument/1.0")]
    public partial class DeliveryAgentHeaderTypeFTPDeliveryAgent : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fTPAddressField;
        
        private string userNameField;
        
        private string passwordField;
        
        private AttachmentType[] attachmentsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FTPAddress {
            get {
                return this.fTPAddressField;
            }
            set {
                this.fTPAddressField = value;
                this.RaisePropertyChanged("FTPAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Attachment", IsNullable=false)]
        public AttachmentType[] Attachments {
            get {
                return this.attachmentsField;
            }
            set {
                this.attachmentsField = value;
                this.RaisePropertyChanged("Attachments");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.courts.mo.gov/exchanges/ExchangeDocument/1.0")]
    public partial class DeliveryAgentHeaderTypeDatabaseDeliveryAgent : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string databaseConnectURLField;
        
        private string databasePersistanceObjectField;
        
        private DeliveryAgentHeaderTypeDatabaseDeliveryAgentMap[] databaseColumnMappingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DatabaseConnectURL {
            get {
                return this.databaseConnectURLField;
            }
            set {
                this.databaseConnectURLField = value;
                this.RaisePropertyChanged("DatabaseConnectURL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DatabasePersistanceObject {
            get {
                return this.databasePersistanceObjectField;
            }
            set {
                this.databasePersistanceObjectField = value;
                this.RaisePropertyChanged("DatabasePersistanceObject");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Map", IsNullable=false)]
        public DeliveryAgentHeaderTypeDatabaseDeliveryAgentMap[] DatabaseColumnMapping {
            get {
                return this.databaseColumnMappingField;
            }
            set {
                this.databaseColumnMappingField = value;
                this.RaisePropertyChanged("DatabaseColumnMapping");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.courts.mo.gov/exchanges/ExchangeDocument/1.0")]
    public partial class DeliveryAgentHeaderTypeDatabaseDeliveryAgentMap : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string columnField;
        
        private string elementField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Column {
            get {
                return this.columnField;
            }
            set {
                this.columnField = value;
                this.RaisePropertyChanged("Column");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Element {
            get {
                return this.elementField;
            }
            set {
                this.elementField = value;
                this.RaisePropertyChanged("Element");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.courts.mo.gov/exchanges/ExchangeDocument/1.0")]
    public partial class DeliveryAgentHeaderTypePrinterDeliveryAgent : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string printerServerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string PrinterServer {
            get {
                return this.printerServerField;
            }
            set {
                this.printerServerField = value;
                this.RaisePropertyChanged("PrinterServer");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.courts.mo.gov/exchanges/ExchangeDocument/1.0")]
    public partial class ExceptionDetailType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string exceptionComponentIDField;
        
        private string exceptionSeverityField;
        
        private string exceptionCodeField;
        
        private string exceptionMessageTextField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ExceptionComponentID {
            get {
                return this.exceptionComponentIDField;
            }
            set {
                this.exceptionComponentIDField = value;
                this.RaisePropertyChanged("ExceptionComponentID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ExceptionSeverity {
            get {
                return this.exceptionSeverityField;
            }
            set {
                this.exceptionSeverityField = value;
                this.RaisePropertyChanged("ExceptionSeverity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ExceptionCode {
            get {
                return this.exceptionCodeField;
            }
            set {
                this.exceptionCodeField = value;
                this.RaisePropertyChanged("ExceptionCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ExceptionMessageText {
            get {
                return this.exceptionMessageTextField;
            }
            set {
                this.exceptionMessageTextField = value;
                this.RaisePropertyChanged("ExceptionMessageText");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.courts.mo.gov/exchanges/ExchangeDocument/1.0")]
    public partial class MoExchangeBusinessExceptionType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string serviceNameField;
        
        private System.DateTime exceptionTimestampField;
        
        private bool exceptionTimestampFieldSpecified;
        
        private object originalPayloadField;
        
        private ExceptionDetailType[] exceptionDetailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ServiceName {
            get {
                return this.serviceNameField;
            }
            set {
                this.serviceNameField = value;
                this.RaisePropertyChanged("ServiceName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime ExceptionTimestamp {
            get {
                return this.exceptionTimestampField;
            }
            set {
                this.exceptionTimestampField = value;
                this.RaisePropertyChanged("ExceptionTimestamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExceptionTimestampSpecified {
            get {
                return this.exceptionTimestampFieldSpecified;
            }
            set {
                this.exceptionTimestampFieldSpecified = value;
                this.RaisePropertyChanged("ExceptionTimestampSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public object OriginalPayload {
            get {
                return this.originalPayloadField;
            }
            set {
                this.originalPayloadField = value;
                this.RaisePropertyChanged("OriginalPayload");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ExceptionDetail", Order=3)]
        public ExceptionDetailType[] ExceptionDetail {
            get {
                return this.exceptionDetailField;
            }
            set {
                this.exceptionDetailField = value;
                this.RaisePropertyChanged("ExceptionDetail");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.courts.mo.gov/exchanges/ExchangeDocument/1.0")]
    public partial class MoExchangeResponsePayloadType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private MoExchangeHeaderType moExchangeHeaderField;
        
        private MoExchangeStructuredDataPayloadType moExchangeStructuredDataPayloadField;
        
        private MoExchangeNotificationType moExchangeNotificationField;
        
        private MoExchangeBusinessExceptionType[] moExchangeExceptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MoExchangeHeaderType MoExchangeHeader {
            get {
                return this.moExchangeHeaderField;
            }
            set {
                this.moExchangeHeaderField = value;
                this.RaisePropertyChanged("MoExchangeHeader");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public MoExchangeStructuredDataPayloadType MoExchangeStructuredDataPayload {
            get {
                return this.moExchangeStructuredDataPayloadField;
            }
            set {
                this.moExchangeStructuredDataPayloadField = value;
                this.RaisePropertyChanged("MoExchangeStructuredDataPayload");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public MoExchangeNotificationType MoExchangeNotification {
            get {
                return this.moExchangeNotificationField;
            }
            set {
                this.moExchangeNotificationField = value;
                this.RaisePropertyChanged("MoExchangeNotification");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("MoExchangeBusinessException", IsNullable=false)]
        public MoExchangeBusinessExceptionType[] MoExchangeException {
            get {
                return this.moExchangeExceptionField;
            }
            set {
                this.moExchangeExceptionField = value;
                this.RaisePropertyChanged("MoExchangeException");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.courts.mo.gov/exchanges/ExchangeDocument/1.0")]
    public partial class MoExchangeStructuredDataPayloadType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string moExchangeStructuredDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MoExchangeStructuredData {
            get {
                return this.moExchangeStructuredDataField;
            }
            set {
                this.moExchangeStructuredDataField = value;
                this.RaisePropertyChanged("MoExchangeStructuredData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="fileNewCase", WrapperNamespace="http://www.courts.mo.gov/exchanges/moecfaf/1.0", IsWrapped=true)]
    public partial class fileNewCaseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.courts.mo.gov/exchanges/ExchangeDocument/1.0", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.courts.mo.gov/exchanges/ExchangeDocument/1.0")]
        public MoCourtDocumentUpload.MoExchangeServiceReference.MoExchangeRequestPayloadType MoExchangeRequest;
        
        public fileNewCaseRequest() {
        }
        
        public fileNewCaseRequest(MoCourtDocumentUpload.MoExchangeServiceReference.MoExchangeRequestPayloadType MoExchangeRequest) {
            this.MoExchangeRequest = MoExchangeRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="fileNewCaseResponse", WrapperNamespace="http://www.courts.mo.gov/exchanges/moecfaf/1.0", IsWrapped=true)]
    public partial class fileNewCaseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.courts.mo.gov/exchanges/ExchangeDocument/1.0", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.courts.mo.gov/exchanges/ExchangeDocument/1.0")]
        public MoCourtDocumentUpload.MoExchangeServiceReference.MoExchangeResponsePayloadType MoExchangeResponse;
        
        public fileNewCaseResponse() {
        }
        
        public fileNewCaseResponse(MoCourtDocumentUpload.MoExchangeServiceReference.MoExchangeResponsePayloadType MoExchangeResponse) {
            this.MoExchangeResponse = MoExchangeResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="fileOnExistingCase", WrapperNamespace="http://www.courts.mo.gov/exchanges/moecfaf/1.0", IsWrapped=true)]
    public partial class fileOnExistingCaseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.courts.mo.gov/exchanges/ExchangeDocument/1.0", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.courts.mo.gov/exchanges/ExchangeDocument/1.0")]
        public MoCourtDocumentUpload.MoExchangeServiceReference.MoExchangeRequestPayloadType MoExchangeRequest;
        
        public fileOnExistingCaseRequest() {
        }
        
        public fileOnExistingCaseRequest(MoCourtDocumentUpload.MoExchangeServiceReference.MoExchangeRequestPayloadType MoExchangeRequest) {
            this.MoExchangeRequest = MoExchangeRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="fileOnExistingCaseResponse", WrapperNamespace="http://www.courts.mo.gov/exchanges/moecfaf/1.0", IsWrapped=true)]
    public partial class fileOnExistingCaseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.courts.mo.gov/exchanges/ExchangeDocument/1.0", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.courts.mo.gov/exchanges/ExchangeDocument/1.0")]
        public MoCourtDocumentUpload.MoExchangeServiceReference.MoExchangeResponsePayloadType MoExchangeResponse;
        
        public fileOnExistingCaseResponse() {
        }
        
        public fileOnExistingCaseResponse(MoCourtDocumentUpload.MoExchangeServiceReference.MoExchangeResponsePayloadType MoExchangeResponse) {
            this.MoExchangeResponse = MoExchangeResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FilingServicePortTypeChannel : MoCourtDocumentUpload.MoExchangeServiceReference.FilingServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FilingServicePortTypeClient : System.ServiceModel.ClientBase<MoCourtDocumentUpload.MoExchangeServiceReference.FilingServicePortType>, MoCourtDocumentUpload.MoExchangeServiceReference.FilingServicePortType {
        
        public FilingServicePortTypeClient() {
        }
        
        public FilingServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FilingServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FilingServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FilingServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MoCourtDocumentUpload.MoExchangeServiceReference.fileNewCaseResponse MoCourtDocumentUpload.MoExchangeServiceReference.FilingServicePortType.fileNewCase(MoCourtDocumentUpload.MoExchangeServiceReference.fileNewCaseRequest request) {
            return base.Channel.fileNewCase(request);
        }
        
        public MoCourtDocumentUpload.MoExchangeServiceReference.MoExchangeResponsePayloadType fileNewCase(MoCourtDocumentUpload.MoExchangeServiceReference.MoExchangeRequestPayloadType MoExchangeRequest) {
            MoCourtDocumentUpload.MoExchangeServiceReference.fileNewCaseRequest inValue = new MoCourtDocumentUpload.MoExchangeServiceReference.fileNewCaseRequest();
            inValue.MoExchangeRequest = MoExchangeRequest;
            MoCourtDocumentUpload.MoExchangeServiceReference.fileNewCaseResponse retVal = ((MoCourtDocumentUpload.MoExchangeServiceReference.FilingServicePortType)(this)).fileNewCase(inValue);
            return retVal.MoExchangeResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MoCourtDocumentUpload.MoExchangeServiceReference.fileNewCaseResponse> MoCourtDocumentUpload.MoExchangeServiceReference.FilingServicePortType.fileNewCaseAsync(MoCourtDocumentUpload.MoExchangeServiceReference.fileNewCaseRequest request) {
            return base.Channel.fileNewCaseAsync(request);
        }
        
        public System.Threading.Tasks.Task<MoCourtDocumentUpload.MoExchangeServiceReference.fileNewCaseResponse> fileNewCaseAsync(MoCourtDocumentUpload.MoExchangeServiceReference.MoExchangeRequestPayloadType MoExchangeRequest) {
            MoCourtDocumentUpload.MoExchangeServiceReference.fileNewCaseRequest inValue = new MoCourtDocumentUpload.MoExchangeServiceReference.fileNewCaseRequest();
            inValue.MoExchangeRequest = MoExchangeRequest;
            return ((MoCourtDocumentUpload.MoExchangeServiceReference.FilingServicePortType)(this)).fileNewCaseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MoCourtDocumentUpload.MoExchangeServiceReference.fileOnExistingCaseResponse MoCourtDocumentUpload.MoExchangeServiceReference.FilingServicePortType.fileOnExistingCase(MoCourtDocumentUpload.MoExchangeServiceReference.fileOnExistingCaseRequest request) {
            return base.Channel.fileOnExistingCase(request);
        }
        
        public MoCourtDocumentUpload.MoExchangeServiceReference.MoExchangeResponsePayloadType fileOnExistingCase(MoCourtDocumentUpload.MoExchangeServiceReference.MoExchangeRequestPayloadType MoExchangeRequest) {
            MoCourtDocumentUpload.MoExchangeServiceReference.fileOnExistingCaseRequest inValue = new MoCourtDocumentUpload.MoExchangeServiceReference.fileOnExistingCaseRequest();
            inValue.MoExchangeRequest = MoExchangeRequest;
            MoCourtDocumentUpload.MoExchangeServiceReference.fileOnExistingCaseResponse retVal = ((MoCourtDocumentUpload.MoExchangeServiceReference.FilingServicePortType)(this)).fileOnExistingCase(inValue);
            return retVal.MoExchangeResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MoCourtDocumentUpload.MoExchangeServiceReference.fileOnExistingCaseResponse> MoCourtDocumentUpload.MoExchangeServiceReference.FilingServicePortType.fileOnExistingCaseAsync(MoCourtDocumentUpload.MoExchangeServiceReference.fileOnExistingCaseRequest request) {
            return base.Channel.fileOnExistingCaseAsync(request);
        }
        
        public System.Threading.Tasks.Task<MoCourtDocumentUpload.MoExchangeServiceReference.fileOnExistingCaseResponse> fileOnExistingCaseAsync(MoCourtDocumentUpload.MoExchangeServiceReference.MoExchangeRequestPayloadType MoExchangeRequest) {
            MoCourtDocumentUpload.MoExchangeServiceReference.fileOnExistingCaseRequest inValue = new MoCourtDocumentUpload.MoExchangeServiceReference.fileOnExistingCaseRequest();
            inValue.MoExchangeRequest = MoExchangeRequest;
            return ((MoCourtDocumentUpload.MoExchangeServiceReference.FilingServicePortType)(this)).fileOnExistingCaseAsync(inValue);
        }
    }
}
